### ISSUE TITLE
Install improvement - Windows

### ISSUE THREAD

**Issue by liamcleland999** [input-output-hk/shelley-testnet#55]
HI, 

1) The install instructions don't mention that Windows powershell requires a ./ for all the commands

./jcli key generate --type=Ed25519Extended > receiver_secret.key
cat receiver_secret.key | ./jcli key to-public > receiver_public.key
./jcli address account --testing $(cat receiver_public.key) | tee receiver_account.txt

2) Also, I don't see the guide on how to SEND via console 

3) is it possible to provide a few stake_pool.id (its not so easy to find)

**Comment by LeaderOfChampions** [comment]
100% agree with appending the **./** to documentation as I was stumped for far longer then I care to admit.

**Comment by liamcleland999** [comment]
Me too :)

**Comment by dorin100** [comment]
1. documentation should be updated with how to run linux like commands on windows (for creating address in this case)
2. @liamcleland999  - it is not clear what you want to send... funds or certificate? For certificate there is a guide here (https://github.com/input-output-hk/shelley-testnet/wiki/How-to-send-a-Certificate-to-the-blockchain-using-the-command-line); for funds, there is one to come.
3. this is quite easy 
```
jcli rest v0 stake get --host "http://127.0.0.1:9000/api"
---
epoch: 220
stake:
  dangling: 0
  pools:
    - - 631665a4194feb55c8250ed3565c4201702f11fa6a91e9485e239f253d72ad4a
      - 259999977900
    - - e680a68e3e822bef51943dab34468e1d9e459b6a136cce505d3d0715e744028c
      - 249999977900
    - - 465f3b0e7b1e8124b45cbdc9bf73a84e82d25ce91295799dbe0acb5a807b3af3
      - 0
    - - c33ab94e9eb40f5792fe980d43bbe3a5747a3dbb8bdebfd3dff592526e85804f
      - 0
    - - 49786e8b516664f38877cbf62a94b02a263a48e577673f3fe7c62dda34271031
      - 0
    - - 3f9f792eb7b6b021c8b9b831931e89373e6b3aa217cfd2da9ef4a852e11bcba6
      - 1999998976800
    - - 307dbb8e494585db96cf9ac4b58690dd5e95d6d56558866acc568e5997117ffb
      - 0
    - - b44323bb90528374556a02941b8056228a2ae798c40ebaadf68cdb65ec80c173
      - 0
    - - 14218575ebb11aa40cc6d4183ca2590ae8cf7ca9fc00d41c5e81d0c8b4a52f59
      - 0
    - - beed1041c9f93d64880809c0bb3bc9c4bbd1668e3e2b139cce972a60cc445aec
      - 0
    - - da2d5f25f4d538b7a2c99ef41d2127444428de19be327282473db763442ad61d
      - 50509999988950
    - - 08706e036b37f640c25d1c24dcd736502b7c1b594de593136ea830b9f306baf6
      - 0
    - - 53a1d75955eff9891f72d6ade78b45a9c6ca8e0f7498ef29e8b4fdcb5f13aa94
      - 16839999824000
    - - 2fa5db57f81c75126b6349f429370e277ed86c351e7e68beda34de41458937f6
      - 0
    - - d4aaee62a66912e4687fc89aec250c8d1e9bb12bd9ebabc285234582864f6a27
      - 249999987850
    - - b371c9090517bd93d2756f0434a4a2a4bcaa768f3d5d5156a7a9dcda7ceec2fa
      - 0
    - - da0ed0ed3d82b70598cd277e78975201c3d194d91eed9ed197e2ed6465758477
      - 509999953600
    - - b7b132fdff13b998da3313c93ce36a75e2ca2f52288e95d944c9a6d6ba9042f3
      - 599999988950
    - - 969963a8b6cab96be257a37f2f27be6cc41c9561253b4da7c47704036024169a
      - 4274999834250
  unassigned: 24504997352700
```
