### ISSUE TITLE
blockRecvCnt: 0 and block creation times out / transfer funds times out

### ISSUE THREAD

**Issue by Dmindfuse** [input-output-hk/shelley-testnet#91]
**Describe the bug
After starting Jormungandr and running it for at least 10 minutes the blockRecvCnt remains at 0. I am able to create addresses, I am able to transfer funds from the faucet to the created addresses, but I cannot transfer funds between addresses on the account of no new block created/time out.

** Prerequisites information

1. What is your Operating system? 
$ cat /proc/version_signature 
Ubuntu 4.4.0-141.167-generic 4.4.162

1. What version of the jormungandr node are you using?  
0.5.5 (HEAD-aec29a1, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
No, download .tar.gz, unpack, overwrite

**To Reproduce
Replaced sensitive info/addresses with "xxx".
1. $ ./jormungandr --config ./node-config.yaml \
--genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 \
--log-level=info
2. wait for "Starting server on 127.0.0.1:3101, scope: global"
3. (assuming 2 addresses created and faucet funds transferred)
4. $ bash send-money.sh <to-address> 50000 3101 <from-key>

> .... send money
> DESTINATION_ADDRESS: xxx
> DESTINATION_AMOUNT: 50000
> REST_PORT: 3101
> SOURCE_SK: xxx
> BLOCK0_HASH: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
> FEE_CONSTANT: 1000
> FEE_COEFFICIENT: 50
> ....
> .. Sending 50000 to xxx
> discrimination: testing
> account: xxx
>  ##1. Create the offline transaction file
>  ##2. Add input details
>  ##3. Add output details
>  ##4. Finalize the transactions
>  ##5. Create the witness
>  ##6. Add the witness to the transaction
>  ##7. Show the transaction info
> Transaction `c4cf372847c8d6413a988359bd668166079d252802ea7cd17b98ecf78139e0ad' (finalizing)
>   Input:   51100
>   Output:  50000
>   Fees:    1100
>   Balance: 0
>  - xxx 51100
>  + xxx 50000
>  ##7. Finalize the transaction and send it
> 69f2fd5fa63cb3398657cf97bdb06ba1fb8c61a8b1ae45ab661241e0df13a5f5
>  ##8. Remove the temporary files
>   ##Waiting for new block to be created (timeout = 200 blocks = 400s)
>   ##ERROR: Waited 2s secs (1*2) and no new block created
> 

**Expected behavior
Block created and funds transferred. blockRecvCnt +1?

**Additional context
blockRecvCnt remains at 0 seemingly infinitely.

> Every 20,0s: ./jcli rest v0 node stats get --host http://127.0.0.1:3101/api                    Fri Oct  4 20:22:31 2019
> 
> ---
> blockRecvCnt: 0
> lastBlockDate: "224.18007"
> lastBlockFees: 0
> lastBlockHash: 3d772fbc1036a5df5ea1716b58802d06eeac5953ec365beff41c54756d3188ef
> lastBlockHeight: "51385"
> lastBlockSum: 0
> lastBlockTime: ~
> lastBlockTx: 0
> txRecvCnt: 1
> uptime: 1717
>

**Comment by dorin100** [comment]
Hi @Dmindfuse . You are experiencing exactly https://github.com/input-output-hk/jormungandr/issues/860

Some background can be found here - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60

This can be helpfull too - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60

**Comment by Dmindfuse** [comment]
@dorin100 , thanks, I take away 2 things from your update:
1. Try it with the extenral and local IP addresses as suggested
2. Consider updates to a local firewall (NAT/Port forwarding)

whereby item number 2 would be worth a mention in the setup instructions if it becomes a permanent necessity. I'll report back what I experienced.

**Comment by Dmindfuse** [comment]
@dorin100 , so I had to do 2 things:

1. I updated my configuration file to the following:
```
log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3101"
  public_address: "/ip4/<mypublicip>/tcp/3101"
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3102"
storage: "/tmp/jormungandr"
```

2. I created a Port Forward rule on my router from any/any:3101 to my local ip:3101.

Jormungandr is now syncing perfectly:

```
Every 20,0s: ./jcli rest v0 node stats get --host http...  Sun Oct  6 12:11:54 2019
---
blockRecvCnt: 1
lastBlockDate: "226.4106"
lastBlockFees: 0
lastBlockHash: c4b44d71944d511470dcacb4bf53a24e900f7c5b4c34dc4d9a55edd5b45fe1bb
lastBlockHeight: "61920"
lastBlockSum: 0
lastBlockTime: "2019-10-06T10:10:26+00:00"
lastBlockTx: 0
txRecvCnt: 1
uptime: 233
```
